{
 "title": "Libvirt Dashboard",
 "description": "\nhttps://github.com/ycy1766/prometheus-libvirt-exporter",
 "tags": [ "libvirt" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "project_name", "query": "label_values(project_name)" },
   {
    "name": "compute_node",
    "query": "label_values(libvirt_domain_info_memory_usage_bytes{job=\"prometheus-libvirt-exporter\", project_name=\"$project_name\"}, instance)"
   },
   {
    "name": "vm_name",
    "query": "label_values(libvirt_domain_info_memory_usage_bytes{job=\"prometheus-libvirt-exporter\",project_name=\"$project_name\",instance=~\"$compute_node\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total maximum_memory_bytes  usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_maximum_memory_bytes{instance=~\"$compute_node\"})"
    }
   ]
  },
  {
   "title": "Total vCPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_virtual_cpus{instance=~\"$compute_node\",name=~\"$vm_name\"})"
    }
   ]
  },
  {
   "title": "libvirt_domain_info_cpu_time_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_info_cpu_time_seconds_total{name=~\"$vm_name\"}[5m]))",
     "legendFormat": "memory_usage_bytes"
    }
   ]
  },
  {
   "title": "libvirt_domain_info_memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_memory_usage_bytes{name=~\"$vm_name\"})",
     "legendFormat": "memory_usage_bytes"
    }
   ]
  },
  {
   "title": "Total memory_usage_bytes  usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_memory_usage_bytes{instance=~\"$compute_node\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Read/Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_bytes_total{name=~\"$vm_name\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_bytes_total{name=~\"$vm_name\"}[5m]))",
     "legendFormat": "Write "
    }
   ]
  },
  {
   "title": "Block Read/Write Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_requests_total{name=~\"$vm_name\"}[5m]))",
     "legendFormat": "Read Requests"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_requests_total{name=~\"$vm_name\"}[5m]))",
     "legendFormat": "Write  Requests"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "interface_stats_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_bytes_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX "
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_bytes_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Interface PPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_packets_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_packets_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "Interface Error/Drop",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_drops_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX Drop"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_drops_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX Drop"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_errors_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_errors_total{name=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX Error"
    }
   ]
  }
 ]
}