---
global:
  resolve_timeout: 5m

route:
  receiver: default-receiver
  group_by: [alertname, datacenter, app]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: default-receiver
  - name: email-notifications
    email_configs:
      - to: alerts@yourdomain.org
        from: prometheus-alerts@{{ inventory_hostname }}
        smarthost: localhost:25
        send_resolved: true
  - name: slack-notifications
    slack_configs:
      - api_url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
        channel: '#vg-lab-notifications'
        title: '{% raw %}{{ .GroupLabels.alertname }} alert{% endraw %}'
        text: '{% raw %}{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}{% endraw %}'
        send_resolved: true
