{% if groups.get('ceph') %}
scrape_configs:
  - job_name: ceph_nodeexporter
    static_configs:
      - targets:
{% for host in groups['ceph'] %}
        - "{{ api_interface_address }}:9100"
{% endfor %}
{% endif %}
