---
- name: Redfish-Exporter
  hosts: monitoring[0]
  gather_facts: false
  tasks:
    - name: Copy redfish-exporter dockerfile
      ansible.builtin.copy:
        src: "{{playbook_dir}}/dockerfiles/redfish-exporter.Dockerfile"
        dest: /opt/kayobe/redfish-exporter.Dockerfile
        mode: 0640

    - name: Copy redfish-exporter.yml to prometheus-server
      become: true
      ansible.builtin.copy:
        dest: /etc/kolla/prometheus-server/redfish-exporter.yml
        content: |-
          ---
          hosts:
            default:
              username: "{{ ipmi_username }}"
              password: "{{ ipmi_password }}"
        mode: 0640

    - name: Build docker image
      become: true
      community.docker.docker_image:
        name: redfish-exporter
        build:
          dockerfile: redfish-exporter.Dockerfile
          pull: false
          path: /opt/kayobe/
          network: host
        source: build

    - name: Create docker container
      become: true
      community.docker.docker_container:
        name: redfish-exporter
        image: redfish-exporter
        command: ./main --config.file /redfish-exporter.yml
        volumes: /etc/kolla/prometheus-server/redfish-exporter.yml:/redfish-exporter.yml:ro
        network_mode: host
        restart_policy: unless-stopped
