---
- hosts: monitoring[0]
  gather_facts: false
  tasks:
   - ansible.builtin.copy:
       src: "{{playbook_dir}}/dockerfiles/redfish-exporter.Dockerfile"
       dest: /opt/kayobe/redfish-exporter.Dockerfile

   - ansible.builtin.copy:
       dest: /etc/kolla/prometheus-server/redfish-exporter.yml
       content: |-
         ---
         hosts:
           default:
             username: "{{ ipmi_username }}"
             password: "{{ ipmi_password }}"
     become: true

   - community.docker.docker_image:
      name: redfish-exporter
      build:
        dockerfile: redfish-exporter.Dockerfile
        pull: false
        path: /opt/kayobe/
        network: host
      source: build
     become: true

   - community.docker.docker_container:
       name: redfish-exporter
       image: redfish-exporter
       command: ./main --config.file /redfish-exporter.yml
       volumes: /etc/kolla/prometheus-server/redfish-exporter.yml:/redfish-exporter.yml:ro
       network_mode : host
       restart_policy: unless-stopped
     become: true
